version: '3.8'

services:
  # --- 1. BACKEND (Node.js) ---
  backend:
    build: ./Backend
    container_name: uce_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      # --- SQL ---
      - DB_HOST=postgres_db
      - DB_USER=admin_sql
      - DB_PASSWORD=password_sql
      - DB_NAME=uce_main_db
      - DB_PORT=5432
      # --- REDIS ---
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
      # --- GENERAL ---
      - JWT_SECRET=uce_secreto_super_seguro
      # Carpeta donde se guardarán las imágenes
      - UPLOAD_PATH=/app/public/uploads
    volumes:
      - ./Backend:/app
      - /app/node_modules
      - ./uploads:/app/public/uploads
    command: npx nodemon index.js
    depends_on:
      - postgres_db
      - redis_cache

  # --- 2. FRONTEND (React) ---
  frontend:
    build: ./Frontend
    container_name: uce_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./Frontend/src:/app/src
    depends_on:
      - backend

  # --- 3. BASE DE DATOS SQL (Postgres) ---
  postgres_db:
    image: postgres:15-alpine
    container_name: uce_sql
    restart: always
    environment:
      POSTGRES_USER: admin_sql
      POSTGRES_PASSWORD: password_sql
      POSTGRES_DB: uce_main_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # --- 4. VISOR SQL (PgAdmin) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: uce_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin-mapa@uce.edu.ec
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db

  # --- 5. CACHÉ (Redis) ---
  redis_cache:
    image: redis:alpine
    container_name: uce_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data: