version: '3.8'

services:
  # --- 1. BACKEND (Node.js) ---
  backend:
    build: ./Backend
    container_name: uce_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      # OJO: Aquí 'DB_HOST' ya no es localhost, sino el nombre del servicio 'postgres_db'
      - DB_HOST=postgres_db
      - DB_USER=admin_sql
      - DB_PASSWORD=password_sql
      - DB_NAME=uce_main_db
      - DB_PORT=5432
      - JWT_SECRET=uce_secreto_super_seguro
    volumes:
      - ./Backend:/app
      # Esto excluye node_modules del túnel para no mezclar librerías de Windows con Linux
      - /app/node_modules
    # Usamos npx nodemon para que reinicie el servidor al detectar cambios
    command: npx nodemon index.js
    depends_on:
      - postgres_db # Espera a que la BD inicie

  # --- 2. FRONTEND (React) ---
  frontend:
    build: ./Frontend
    container_name: uce_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      # Esto es para que Vite sepa dónde vigilar cambios (Hot Reload)
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Este truco permite que si cambias código en tu Windows, se actualice en el Docker al instante
      - ./Frontend/src:/app/src
    depends_on:
      - backend

  # --- 3. BASE DE DATOS SQL ---
  postgres_db:
    image: postgres:15-alpine
    container_name: uce_sql
    restart: always
    environment:
      POSTGRES_USER: admin_sql
      POSTGRES_PASSWORD: password_sql
      POSTGRES_DB: uce_main_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # --- 4. VISOR SQL (PgAdmin) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: uce_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@uce.edu.ec
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db

  # --- 5. BASE DE DATOS NOSQL ---
  mongo_db:
    image: mongo:6.0
    container_name: uce_nosql
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_mongo
      MONGO_INITDB_ROOT_PASSWORD: password_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # --- 6. VISOR MONGO ---
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin_mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: password_mongo
      ME_CONFIG_MONGODB_URL: mongodb://admin_mongo:password_mongo@mongo_db:27017/
    depends_on:
      - mongo_db

volumes:
  pg_data:
  mongo_data:
